"use client"
// import { ThemeProvider } from "./components/ui/theme-provider"
import { ThemeProvider } from "next-themes"

import "./styles/globals.css"
import { Space_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const space_mono = Space_Mono({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-space-mono",
});


export const metadata = {
  title: 'Github finder',
  description: 'Generated by blog',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${space_mono.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="min-h-screen h-full bg-secondary font-mono">
            <div className="mx-auto max-w-[360px] pt-8 md:max-w-[573px] lg:max-w-[730px]">
              {children}
            </div>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
